openapi: 3.0.3
info:
  title: Swagger JEWELRY SHOP - OpenAPI 3.0
  description: |-
    PROJECT SDN
  termsOfService: https://docs.google.com/spreadsheets/d/1R2fpNLx-H0VYpIQADfsMWJ_1F9cbCukkhc7RkuMsX0k/edit#gid=0
  contact:
    email: maitranhuy1709@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:9999/api/v1/
tags:
  - name: users
    description: Các API LIÊN QUAN ĐẾN USER

paths:
  /users/:
    get:
      tags:
        - users
      summary: Get all các user
      description: Get all user trong JEWELRY shop
      operationId: getAllUser  
      responses:
        "200":
          description: Get All successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/login:
    post:
      tags:
        - users
      summary: Login
      description: Login into JEWELRY shop
      operationId: login
      requestBody:
        description: Account to login
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  format: email
                  example: abc@example.com
                userPassword:
                  type: string
                  example: example.com    
        required: true
      responses:
        "200":
          description: Login successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"

        "403":
          description: Bị từ chối truy cập
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Bị từ chối truy cập"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/logout:
    get: 
      tags:
        - users
      summary: Đăng xuất tài khoản
      description: Đăng xuất tài khoản trong JEWELRY shop
      operationId: logout
      responses:
        "200":
          description: Đăng xuất thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LogoutSuccess"
        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/register:
    post:
      tags:
        - users
      summary: Đăng ký tài khoản
      description: Đăng ký tài khoản mới trong JEWELRY shop
      operationId: register
      requestBody:
        description: Thông tin tài khoản cần đăng ký
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: John 
                userEmail:
                  type: string
                  format: email
                  example: example@example@example
                userPassword:
                  type: string
                  example: example
                confirmPassword:
                  type: string
                  example: example
                userPhoneNumber:
                  type: string
                  example: 01234576454
                userGender:
                  type: string
                  example: Male
                userAddress:
                  type: string
                  example: Somewhere
                userAge:
                  type: integer
                  example: 21
        required: true
      responses:
        "200":
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterSuccess"
        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/verify:
    get:
      tags:
        - users
      summary: Xác minh tài khoản
      description: Xác minh tài khoản trong JEWELRY shop
      operationId: verify
      parameters:
        - name: userEmail
          in: query
          description: Địa chỉ email của người dùng cần xác minh
          required: true
          schema:
            type: string
            example: example@example.com
      responses:
        "200":
          description: Xác minh thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifySuccess"
        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/forgotPassword:
    get:
      tags:
        - users
      summary: Forgot mật khẩu tài khoản
      description: Forgot mật khẩu tài khoản trong JEWELRY shop
      operationId: forgotPassword  
      parameters:
        - name: userEmail
          in: query
          description: Địa chỉ email của người dùng cần xác minh
          required: true
          schema:
            type: string
            example: example@example.com
      responses:
        "200":
          description: Forgot Password successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForgotPasswordSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"       
  /users/resetPassword:
    put:
      tags:
        - users
      summary: Reset mật khẩu tài khoản
      description: Reset mật khẩu tài khoản trong JEWELRY shop
      operationId: resetPassword  
      requestBody:
        description: Reset password
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  example: example123 
                userPasswordResetToken:
                  type: string
                  example: dfsdf23423sdasdfasdf     
        required: true
      responses:
        "200":
          description: Change Password successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResetPasswordSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"  
  /users/changePassword:
    put:
      tags:
        - users
      summary: Đổi mật khẩu tài khoản
      description: Đổi mật khẩu tài khoản trong JEWELRY shop
      operationId: changePassword 
      security:  
       - BearerAuth: []
      requestBody:
        description: Change password
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  example: example
                newPassword:
                  type: string
                  example: example123 
                confirmPassword:
                  type: string
                  example: example123     
        required: true
      responses:
        "200":
          description: Change Password successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChangePasswordSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/viewProfile:
    get:
      tags:
        - users
      summary: Lấy thông tin người dùng
      description: Lấy thông tin người dùng trong JEWELRY shop
      operationId: viewProfile  
      responses:
        "200":
          description: View profile successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ViewProfileSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/updateProfile:
    put:
      tags:
        - users
      summary: Đổi thông tin tài khoản
      description: Đổi thông tin tài khoản trong JEWELRY shop
      operationId: updateProfile
      security:  
       - BearerAuth: []  
      requestBody:
        description: Change profile
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: John Doe
                userPhoneNumber:
                  type: string
                  example: +1234567890
                userGender:
                  type: string
                  enum:
                    - Male
                    - Female
                  example: Male
                userAddress:
                  type: string
                  example: 123 Main St, City
                userAge:
                  type: integer
                  example: 30
                userAvatar:
                  type: string
                  example: https://example.com/avatar.jpg
              required:
                - userEmail
      responses:
        "200":
          description: Update profile successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateProfileSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/updateRole:
    put:
      tags:
        - users
      summary: Đổi role tài khoản
      description: Đổi role tài khoản trong JEWELRY shop
      operationId: updateRole
      security:  
       - BearerAuth: []  
      requestBody:
        description: Change Role
        content:
          application/json:
            schema:
              type: object
              properties:
                newRole:
                  type: number
                  example: 1
        required: true
      responses:
        "200":
          description: Update role successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateRoleSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/updateStatus:
    put:
      tags:
        - users
      summary: Đổi status tài khoản
      description: Đổi status tài khoản trong JEWELRY shop
      operationId: updateStatus
      security:  
       - BearerAuth: []  
      requestBody:
        description: Change Status
        content:
          application/json:
            schema:
              type: object
              properties:
                newStatus:
                  type: boolean
                  example: false
        required: true
      responses:
        "200":
          description: Update status successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateStatusSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
  /users/updateBlock:
    put:
      tags:
        - users
      summary: Đổi Block tài khoản
      description: Đổi Block tài khoản trong JEWELRY shop
      operationId: updateBlock
      security:  
       - BearerAuth: []  
      requestBody:
        description: Change Block
        content:
          application/json:
            schema:
              type: object
              properties:
                newBlock:
                  type: boolean
                  example: false
        required: true
      responses:
        "200":
          description: Update block successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateBlockSuccess"

        "400":
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorRequest"
        "500":
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorServer"
 